on: push

jobs:
  zip:
    name: zip
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          sh zip.sh

          git config user.name github-actions
          git config user.email github-actions@github.com

          echo "Skipping tracked zip files:"
          for entry in `git diff --name-only`
          do
          if [[ $entry =~ [.]zip$ ]]; then
            echo "  ¬ $entry"
            git checkout -- $entry
          fi
          done

          if [[ $(git status -s) ]]; then
            echo "Adding untracked zip files:"
            for entry in `git ls-files -o --exclude-standard`
            do
            if [[ $entry =~ [.]zip$ ]]; then
              echo "  ¬ $entry"
              git add $entry
            fi
            done
            git commit -m 'chore: update zip files'
            git push
          else
            echo "No zip files left to commit."
          fi
