on: workflow_dispatch

jobs:
  zip:
    name: zip
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          sh ./zip.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add '*.zip'
          git commit -m 'chore":" update zip files'
          git push
