on: push

jobs:
  zip:
    name: zip
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          sh ./zip.sh

          git config user.name github-actions
          git config user.email github-actions@github.com

          for entry in `git diff --name-only`
          do
          if [[ $entry =~ [.]zip$ ]]; then
            echo "  ¬ $entry is already stored in git. Skipping update."
            git checkout -- $entry
          fi
          done

          if [[ $(git status -s) ]]; then
            git add $(git ls-files -o --exclude-standard)
            git commit -m 'chore: update zip files'
            git push
          else
            echo "No changes to commit."
          fi
