on: workflow_dispatch

jobs:
  zip:
    name: zip
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          sh ./zip.sh

          git config user.name github-actions
          git config user.email github-actions@github.com

          for y in `git diff --name-only`
          do
          if [[ $y =~ [.]zip$ ]]; then
            echo "Staging $y..."
            git add $y;
          fi
          done

          git add $(git ls-files -o --exclude-standard)
          git commit -m 'chore: update zip files'
          git push
